const TICKET_CATEGORIES = {
  GENERAL: 'GENERAL',
  SUPPORT: 'SUPPORT',
  BOOKING: 'BOOKING',
  COMPLAINT: 'COMPLAINT',
  REFUND: 'REFUND',
  TECHNICAL: 'TECHNICAL',
  BILLING: 'BILLING',
  FEEDBACK: 'FEEDBACK',
  OTHER: 'OTHER',
};

const TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

const TICKET_STATUS = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_CUSTOMER: 'WAITING_CUSTOMER',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
};

const TICKET_SOURCE = {
  AI: 'AI',
  EXECUTIVE: 'EXECUTIVE',
  ADMINISTRATOR: 'ADMINISTRATOR',
  VISITOR_REQUEST: 'VISITOR_REQUEST',
};

// TICKET_SYSTEM.md §4/§9: "Only valid transitions are permitted." Keys are
// the current status; values are the statuses it may move to next.
const VALID_STATUS_TRANSITIONS = {
  [TICKET_STATUS.OPEN]: [TICKET_STATUS.ASSIGNED, TICKET_STATUS.CLOSED],
  [TICKET_STATUS.ASSIGNED]: [TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.OPEN, TICKET_STATUS.CLOSED],
  [TICKET_STATUS.IN_PROGRESS]: [
    TICKET_STATUS.WAITING_CUSTOMER,
    TICKET_STATUS.RESOLVED,
    TICKET_STATUS.CLOSED,
  ],
  [TICKET_STATUS.WAITING_CUSTOMER]: [TICKET_STATUS.IN_PROGRESS, TICKET_STATUS.RESOLVED, TICKET_STATUS.CLOSED],
  [TICKET_STATUS.RESOLVED]: [TICKET_STATUS.CLOSED, TICKET_STATUS.REOPENED],
  [TICKET_STATUS.CLOSED]: [TICKET_STATUS.REOPENED],
  [TICKET_STATUS.REOPENED]: [TICKET_STATUS.ASSIGNED, TICKET_STATUS.IN_PROGRESS],
};

const TICKET_AUDIT_ACTIONS = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  REASSIGNED: 'REASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  NOTE_ADDED: 'NOTE_ADDED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  RESTORED: 'RESTORED',
};

module.exports = {
  TICKET_CATEGORIES,
  TICKET_PRIORITY,
  TICKET_STATUS,
  TICKET_SOURCE,
  VALID_STATUS_TRANSITIONS,
  TICKET_AUDIT_ACTIONS,
};
