const { ROLES } = require('./roles');

const PERMISSIONS = {
  ACCEPT_CHAT: 'ACCEPT_CHAT',
  VIEW_OWN_CONVERSATION: 'VIEW_OWN_CONVERSATION',
  MANAGE_TICKETS: 'MANAGE_TICKETS',
  VIEW_KNOWLEDGE_BASE: 'VIEW_KNOWLEDGE_BASE',
  MANAGE_KNOWLEDGE_BASE: 'MANAGE_KNOWLEDGE_BASE',
  MANAGE_BUSINESS_HOURS: 'MANAGE_BUSINESS_HOURS',
  MANAGE_EXECUTIVES: 'MANAGE_EXECUTIVES',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  CONFIGURE_AI: 'CONFIGURE_AI',
  MANAGE_WIDGET_SETTINGS: 'MANAGE_WIDGET_SETTINGS',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_LEADS: 'MANAGE_LEADS',
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_OWN_CONVERSATION,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.VIEW_KNOWLEDGE_BASE,
    PERMISSIONS.MANAGE_KNOWLEDGE_BASE,
    PERMISSIONS.MANAGE_BUSINESS_HOURS,
    PERMISSIONS.MANAGE_EXECUTIVES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.CONFIGURE_AI,
    PERMISSIONS.MANAGE_WIDGET_SETTINGS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_LEADS,
  ],
  [ROLES.EXECUTIVE]: [
    PERMISSIONS.ACCEPT_CHAT,
    PERMISSIONS.VIEW_OWN_CONVERSATION,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.VIEW_KNOWLEDGE_BASE,
    PERMISSIONS.MANAGE_LEADS,
  ],
};

function hasPermission(role, permission) {
  return (ROLE_PERMISSIONS[role] || []).includes(permission);
}

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, hasPermission };
