const KNOWLEDGE_CATEGORIES = {
  COMPANY: 'COMPANY',
  SERVICES: 'SERVICES',
  FAQS: 'FAQS',
  LOCATIONS: 'LOCATIONS',
  CONTACT_INFORMATION: 'CONTACT_INFORMATION',
  BUSINESS_HOURS: 'BUSINESS_HOURS',
  PRICING: 'PRICING',
  POLICIES: 'POLICIES',
  PRIVACY_POLICY: 'PRIVACY_POLICY',
  TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
  DEPARTMENTS: 'DEPARTMENTS',
  EXECUTIVES: 'EXECUTIVES',
  LEAD_COLLECTION: 'LEAD_COLLECTION',
  GREETING_MESSAGES: 'GREETING_MESSAGES',
  ESCALATION_RULES: 'ESCALATION_RULES',
  CHATBOT_SETTINGS: 'CHATBOT_SETTINGS',
};

const KNOWLEDGE_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
};

module.exports = { KNOWLEDGE_CATEGORIES, KNOWLEDGE_STATUS };
