const PROMPT_TYPES = {
  SYSTEM: 'SYSTEM',
  DEVELOPER: 'DEVELOPER',
  LEAD: 'LEAD',
  SUMMARY: 'SUMMARY',
  ESCALATION: 'ESCALATION',
  FALLBACK: 'FALLBACK',
};

const PROMPT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
};

module.exports = { PROMPT_TYPES, PROMPT_STATUS };
