const LEAD_SOURCE = {
  AI_CONVERSATION: 'AI_CONVERSATION',
  EXECUTIVE: 'EXECUTIVE',
  ADMINISTRATOR: 'ADMINISTRATOR',
};

const LEAD_SCORE = {
  HOT: 'HOT',
  WARM: 'WARM',
  COLD: 'COLD',
};

const LEAD_STATUS = {
  NEW: 'NEW',
  ASSIGNED: 'ASSIGNED',
  CONTACTED: 'CONTACTED',
  FOLLOW_UP: 'FOLLOW_UP',
  QUALIFIED: 'QUALIFIED',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST',
  ARCHIVED: 'ARCHIVED',
};

// LEAD_MANAGEMENT.md §4/§9: "Status transitions should be validated."
// Keys are the current status; values are the statuses it may move to
// next. ARCHIVED is reachable from (almost) anywhere — Administrators
// can archive a lead at any stage (§13) — and ARCHIVED -> NEW is the
// "Restore Leads" action re-entering the pipeline fresh.
const VALID_STATUS_TRANSITIONS = {
  [LEAD_STATUS.NEW]: [LEAD_STATUS.ASSIGNED, LEAD_STATUS.QUALIFIED, LEAD_STATUS.LOST, LEAD_STATUS.ARCHIVED],
  [LEAD_STATUS.ASSIGNED]: [
    LEAD_STATUS.CONTACTED,
    LEAD_STATUS.QUALIFIED,
    LEAD_STATUS.LOST,
    LEAD_STATUS.ARCHIVED,
  ],
  [LEAD_STATUS.CONTACTED]: [
    LEAD_STATUS.FOLLOW_UP,
    LEAD_STATUS.QUALIFIED,
    LEAD_STATUS.CONVERTED,
    LEAD_STATUS.LOST,
    LEAD_STATUS.ARCHIVED,
  ],
  [LEAD_STATUS.FOLLOW_UP]: [
    LEAD_STATUS.CONTACTED,
    LEAD_STATUS.QUALIFIED,
    LEAD_STATUS.CONVERTED,
    LEAD_STATUS.LOST,
    LEAD_STATUS.ARCHIVED,
  ],
  [LEAD_STATUS.QUALIFIED]: [LEAD_STATUS.CONTACTED, LEAD_STATUS.CONVERTED, LEAD_STATUS.LOST, LEAD_STATUS.ARCHIVED],
  [LEAD_STATUS.CONVERTED]: [LEAD_STATUS.ARCHIVED],
  [LEAD_STATUS.LOST]: [LEAD_STATUS.ARCHIVED, LEAD_STATUS.NEW],
  [LEAD_STATUS.ARCHIVED]: [LEAD_STATUS.NEW],
};

module.exports = { LEAD_SOURCE, LEAD_SCORE, LEAD_STATUS, VALID_STATUS_TRANSITIONS };
